#!/usr/bin/env python3
"""Read scripts/lyrics-align/output/*.json and emit src/lib/musicData.ts.

Run from project root:
    python3 scripts/lyrics-align/emit-ts.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUT_DIR = ROOT / "scripts" / "lyrics-align" / "output"
OUTPUT_FILE = ROOT / "src" / "lib" / "musicData.ts"

# Order matches plan: closer, make-it, open-it, what-good
ORDER = [
    "Open It Up",
    "Closer to the Choice",
    "Make it to the end",
    "What Good Looks Like",
]


def slugify(title: str) -> str:
    s = title.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


def to_ts_str(s: str) -> str:
    # JSON-safe string literal — escape backslash, double-quote, then wrap.
    return json.dumps(s, ensure_ascii=False)


def emit() -> str:
    songs = []
    for title in ORDER:
        path = INPUT_DIR / f"{title}.json"
        data = json.loads(path.read_text())
        slug = slugify(title)
        lines_src = data["lines"]
        line_chunks = []
        for ln in lines_src:
            words_chunks = []
            for w in ln["words"]:
                words_chunks.append(
                    "{w:%s,s:%s,e:%s}"
                    % (to_ts_str(w["word"]), w["start"], w["end"])
                )
            line_chunks.append(
                "{t:%s,s:%s,e:%s,w:[%s]}"
                % (
                    to_ts_str(ln["text"]),
                    ln["start"],
                    ln["end"],
                    ",".join(words_chunks),
                )
            )
        songs.append(
            {
                "id": slug,
                "title": data["title"],
                "audio": f"/music/{slug}.mp3",
                "cover": f"/music/covers/{slug}.jpg",
                "duration": data["duration"],
                "lines_src": line_chunks,
            }
        )

    out = ["// AUTO-GENERATED by scripts/lyrics-align/emit-ts.py — do not edit by hand."]
    out.append("")
    out.append("export type Word = { word: string; start: number; end: number };")
    out.append(
        "export type Line = { text: string; start: number; end: number; words: Word[] };"
    )
    out.append("export type Song = {")
    out.append("  id: string;")
    out.append("  title: string;")
    out.append("  audio: string;")
    out.append("  cover: string;")
    out.append("  duration: number;")
    out.append("  lines: Line[];")
    out.append("};")
    out.append("")
    out.append("type RawWord = { w: string; s: number; e: number };")
    out.append("type RawLine = { t: string; s: number; e: number; w: RawWord[] };")
    out.append("type RawSong = {")
    out.append("  id: string;")
    out.append("  title: string;")
    out.append("  audio: string;")
    out.append("  cover: string;")
    out.append("  duration: number;")
    out.append("  lines: RawLine[];")
    out.append("};")
    out.append("")
    out.append("const RAW: RawSong[] = [")
    for s in songs:
        out.append("  {")
        out.append(f"    id: {to_ts_str(s['id'])},")
        out.append(f"    title: {to_ts_str(s['title'])},")
        out.append(f"    audio: {to_ts_str(s['audio'])},")
        out.append(f"    cover: {to_ts_str(s['cover'])},")
        out.append(f"    duration: {s['duration']},")
        out.append("    lines: [")
        for chunk in s["lines_src"]:
            out.append(f"      {chunk},")
        out.append("    ],")
        out.append("  },")
    out.append("];")
    out.append("")
    out.append("export const SONGS: Song[] = RAW.map((s) => ({")
    out.append("  id: s.id,")
    out.append("  title: s.title,")
    out.append("  audio: s.audio,")
    out.append("  cover: s.cover,")
    out.append("  duration: s.duration,")
    out.append("  lines: s.lines.map((l) => ({")
    out.append("    text: l.t,")
    out.append("    start: l.s,")
    out.append("    end: l.e,")
    out.append("    words: l.w.map((w) => ({ word: w.w, start: w.s, end: w.e })),")
    out.append("  })),")
    out.append("}));")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(emit())
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT)}")
